accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/expenses/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

expenses/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_views
from receipts.views import ReceiptRedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "",
        ReceiptRedirectView.as_view(),
    ),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

receipts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import ExpenseCategory, Account, Receipt
from django.views.generic.base import RedirectView
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class ReceiptRedirectView(RedirectView):
    url = "/receipts/"
    pattern_name = "home"


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        return super().form_valid(form)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_categories/create.html"
    fields = ["name"]
    success_url = reverse_lazy("list_categories")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]
    success_url = reverse_lazy("list_accounts")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

receipts/templates/accounts/create.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div>
        <h1>Create Account</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends "base.html" %}
{% block content %}
  <main>
    <h1>My Expense Categories</h1>
    <p>
        <a href="{% url "create_account" %}">Create Account</a>
    </p>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of Receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for account in account_list %}
                <tr>
                    <td>{{account.name}}</td>
                </tr>
                <tr>
                    <td>{{account.number}}</td>
                </tr>
                <tr>
                    <td>{{account.receipts.all|length}}</td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
  </main>
{% endblock content %}

receipts/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Title</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_anonymous %}
                    <li>
                        <a href="{% url "login" %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url "signup" %}">Signup</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url "list_accounts" %}">Account List</a>
                    </li>
                    <li>
                        <a href="{% url "create_account" %}">Create Account</a>
                    </li>
                    <li>
                        <a href="{% url "list_categories" %}">Category List</a>
                    </li>
                    <li>
                        <a href="{% url "create_category" %}">Create Category</a>
                    </li>
                    <li>
                        <a href="{% url "home" %}">Receipt List</a>
                    </li>
                    <li>
                        <a href="{% url "create_receipt" %}">Create Receipt</a>
                    </li>
                    <li>
                        <a href="{% url "logout" %}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/expense_categories/create.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div>
        <h1>Create Expense Category</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/expense_categories/list.html
{% extends "base.html" %}
{% block content %}
  <main>
    <h1>My Expense Categories</h1>
    <p>
        <a href="{% url "create_category" %}">Create Category</a>
    </p>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of Receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for expense_category in expensecategory_list %}
                <tr>
                    <td>{{expense_category.name}}</td>
                </tr>
                <tr>
                    <td>{{expense_category.receipts.all|length}}</td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
  </main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div>
        <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends "base.html" %}
{% block content %}
  <main>
    <h1>My Receipts</h1>
    <table>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for receipt in receipt_list %}
                <tr>
                    <td>{{receipt.vendor}}</td>
                    <td>{{receipt.total}}</td>
                    <td>{{receipt.tax}}</td>
                    <td>{{receipt.date| date:"m-d-Y"}}</td>
                    <td>{{receipt.category}}</td>
                    <td>{{receipt.account}}</td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
  </main>
{% endblock content %}